apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  labels:
    app: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: simulator
        ports:
        - containerPort: 8080
        env:
        - name: UPDATE_HZ
          value: "6"
        - name: PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: simulator
spec:
  selector:
    app: simulator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP