apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: voyager-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voyager-prometheus
  template:
    metadata:
      labels:
        app: voyager-prometheus
    spec:
      containers:
      - name: prometheus
        image: prometheus
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: voyager-prometheus
  ports:
    - port: 9090
      targetPort: 9090
