apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: voyager-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voyager-loki
  template:
    metadata:
      labels:
        app: voyager-loki
    spec:
      containers:
      - name: loki
        image: loki
        ports:
        - containerPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: voyager-loki
  ports:
    - port: 3100
      targetPort: 3100