apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app: voyager-tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voyager-tempo
  template:
    metadata:
      labels:
        app: voyager-tempo
    spec:
      containers:
      - name: tempo
        image: tempo
        ports:
        - containerPort: 3200
        - containerPort: 4317
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: voyager-tempo
  ports:
    - name: http
      port: 3200
      targetPort: 3200
    - name: otlp-grpc
      port: 4317
      targetPort: 4317