apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: voyager
  region: us-east-1
  version: "1.32"

managedNodeGroups:
  - name: voyager-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 30

iam:
  withOIDC: true
